advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
    #re_path(r'^(?P<pk>\d+)$', views.SchoolDetailView.as_view(), name='detail')
]

advcbv/basic_app/urls.py
from unicodedata import name
from django.urls import include, path, re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]
#

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School (models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__ (self):
        return self.name

    def get_absolute_url(self):
        ''''This method helps us to redirect to another page when we have successfully created the view'''
        return reverse('basic_app:detail', kwargs={'pk':self.pk})
    

class Students(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey('School', related_name='students', on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name  

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from . import models
from django.urls import reverse_lazy

# Create your views here.
'''def index(request):
    return render(request, 'index.html')'''

# Now using class based views 

'''class CBView(View):
    def get(self, request):
        return HttpResponse("<h1> CLASS BASED VIEWS ARE COOL! </h1>")'''

class IndexView (TemplateView):
    template_name = 'index.html'

'''
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['injectme'] = "BASIC INJECTION!"
        return context
'''

class SchoolListView(ListView):
    model = models.School

    # Or we can say context_object_name = 'schools'. In this way we have redefined it to be schools and no longer school_list
    #template_name = 'basic_app/school_list.html'

class SchoolDetailView(DetailView):
    model = models.School
    context_object_name = 'school_detail'
    # but the detail view just turns to lower case but we can choose to redfine our own to what we want

    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">

        <ul class="nav navbar-nav">
            <li><a href="{% url 'basic_app:list' %}" class="navbar-brand">Schools</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
            
        </ul>

    </nav>
    <div class="container">

    {%  block body_block%}

    {% endblock %}

    </div>
</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

    <h1>Delete {{ school.name }}?</h1>
    <form method='post'>
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}

    {% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the School Detail Page!</h1>
        <h2>School Details: </h2>

        <p><strong>Name:</strong> {{ school_detail.name }}</p>
        <p><strong>Principal:</strong> {{ school_detail.principal }}</p>
        <p><strong>Location:</strong> {{ school_detail.location }}</p>
        <h3><strong>Students:</strong> </h3>
        {% for student in school_detail.students.all %}
            <p>{{ student.name }} is {{ student.age }} years old.</p>
        {% endfor %}
    </div>
    <div class="container">
      <p><a href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
        <a href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
    </p>
    </div>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form action="" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<h1>Welcome to a List of all the schools!</h1>
<ol>
    {% for school in school_list %}
    <!--The school list is already defined in the 
    views.py  automatcally i.e python takes the 
model and turns it into small letters and then add  _list to it. But if
we decide to redefine it we can follow the step indicated in the views.py file-->
    <h2><li><a href="/basic_app/{{ school.pk }}">{{ school.name }}</a></li></h2>
    {% endfor %}
</ol>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">

        <ul class="nav navbar-nav">
            <li><a href="{% url 'basic_app:list' %}" class="navbar-brand">Schools</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
        </ul>

    </nav>
    <div class="container">

    {%  block body_block%}

    {% endblock %}

    </div>
</body>
</html>

advcbv/templates/index.html
<!DOCTYPE html>
{% extends  "base.html" %}
{% block body_block %}
    
<div class="jumbotron">
    <h1>HomePage!</h1>
</div>
{% endblock  %}